### ISSUE TITLE
[Feature request] Separate X/Y sensitivities.

### ISSUE THREAD

**Issue by Dext1** [JibbSmart/JoyShockMapper#5]
Can you add this to thumbstick and gyro aiming?

**Comment by JibbSmart** [comment]
Yeah, that shouldn't be too hard. For gyro, it'd probably not be separate sensitivities (since that'll blow up the acceleration settings), but maybe a multiplier that gets applied after regular processing? I'll figure something out.

Just curious -- any particular reason you want separate axis sensitivities for gyro? Do you like to have the same for mouse?

Cheers

**Comment by Dext1** [comment]
Yes, multiplier after accel calculation would probably be best.

I like to have a slower sensitivity for vertical axis because of my wrist range of motion. I draw circles more naturally that way. As for mouse input, I like higher vertical sensitivity for similar reasons.

**Comment by JibbSmart** [comment]
That makes sense. Thanks for the feedback. I'll leave this open until I've actually implemented it.

**Comment by JibbSmart** [comment]
I forgot to include it in the changelog, but 1.5 features this option.
GYRO_SENS = 1 0.5
will set horizontal to 1 and vertical to 0.5. The same works for MIN_GYRO_SENS and MAX_GYRO_SENS. Thanks to @Electronicks for implementing this.
