### ISSUE TITLE
Feature Requests: Graphics User Interface?

### ISSUE THREAD

**Issue by benz-phan** [JibbSmart/JoyShockMapper#57]
Is it that hard to make a graphics user interface?

**Comment by JibbSmart** [comment]
Hi!

A GUI will:
- Take time that can otherwise be spent on new features
- Make it harder to port to other platforms and/or add a lot of bloat to the program
- Make new features take much longer to implement even after the GUI is added, because layout, sub-menus, etc need to be considered for every new feature
- Pretty much just as easily be implemented by someone else as an external program that sends the right text commands to JSM

If you're interested in doing it yourself, I'd first recommend creating something simple that can generate config files, then explore having it interact directly with JSM :)

**Comment by benz-phan** [comment]
Ok thanks a lot @JibbSmart!
